name: Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: jreyes-s
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
